Import Magento\Framework\DB\Select class
This class is used in Model\ResourceModel\Page\Fulltext\Collection::setOrder

Error: Class 'Smile\ElasticsuiteCms\Model\ResourceModel\Page\Fulltext\Select'
not found in vendor/magento/framework/Code/Generator/EntityAbstract.php